const testData = {
  english: [
    { question: "What is the past tense of 'go'?", options: ["go", "went", "going", "gone"], correct: 1 },
    { question: "Which word is spelled correctly?", options: ["recieve", "receive", "receve", "recve"], correct: 1 },
    { question: "What does 'grateful' mean?", options: ["angry", "thankful", "tired", "confused"], correct: 1 },
    { question: "Choose the correct sentence:", options: ["She don't like apples", "She doesn't like apples", "She not like apples", "She not likes apples"], correct: 1 },
    { question: "What is an adjective?", options: ["A word that describes action", "A word that describes a noun", "A word that connects words", "A word that replaces a noun"], correct: 1 },
    { question: "Fill in: 'If I ____ you were coming, I would have prepared.'", options: ["knew", "know", "had known", "have known"], correct: 2 },
    { question: "What is the opposite of 'beautiful'?", options: ["ugly", "nice", "good", "pleasant"], correct: 0 },
    { question: "Choose the right word: 'There / Their / They're going to the park.'", options: ["There", "Their", "They're", "All are correct"], correct: 2 },
    { question: "What does 'abandoned' mean?", options: ["repaired", "left alone", "built", "destroyed"], correct: 1 },
    { question: "Which word is a synonym for 'happy'?", options: ["sad", "joyful", "angry", "tired"], correct: 1 },
    { question: "What is a verb?", options: ["A describing word", "An action word", "A person name", "A place name"], correct: 1 },
    { question: "Fill in: 'She ____ to the store yesterday.'", options: ["go", "goes", "went", "going"], correct: 2 },
    { question: "What does 'brilliant' mean?", options: ["dark", "dull", "very clever", "slow"], correct: 2 },
    { question: "Choose the correct sentence:", options: ["He are a teacher", "He am a teacher", "He is a teacher", "He be a teacher"], correct: 2 },
    { question: "What is an adverb?", options: ["A describing word", "A word that modifies verbs", "A person name", "A thing name"], correct: 1 },
    { question: "Which word is a preposition?", options: ["run", "beautiful", "under", "quickly"], correct: 2 },
    { question: "What does 'sufficient' mean?", options: ["not enough", "enough", "too much", "perfect"], correct: 1 },
    { question: "Fill in: 'I have ____ to Paris twice.'", options: ["go", "going", "gone", "goes"], correct: 2 },
    { question: "Choose the correct tense:", options: ["I eated", "I eat", "I ate", "I am eating"], correct: 2 },
    { question: "What is a pronoun?", options: ["A describing word", "A word that replaces a noun", "An action word", "A place name"], correct: 1 },
    { question: "Which is correct?", options: ["They is here", "They are here", "They be here", "They am here"], correct: 1 },
    { question: "What does 'enormous' mean?", options: ["tiny", "very large", "small", "medium"], correct: 1 },
    { question: "Fill in: 'She ____ never been to London.'", options: ["have", "has", "had", "having"], correct: 1 },
    { question: "Choose the correct article:", options: ["a apple", "an apple", "the apple", "apple"], correct: 1 },
    { question: "What does 'comprehend' mean?", options: ["forget", "understand", "ignore", "avoid"], correct: 1 },
    { question: "Which sentence is correct?", options: ["He don't like pizza", "He doesn't like pizza", "He not like pizza", "He no like pizza"], correct: 1 },
    { question: "What is a noun?", options: ["A person, place, or thing", "An action word", "A describing word", "A connection word"], correct: 0 },
    { question: "What does 'magnificent' mean?", options: ["small", "ugly", "splendid", "ordinary"], correct: 2 },
    { question: "Choose the correct spelling:", options: ["occured", "occurred", "occured", "occured"], correct: 1 },
    { question: "What does 'patient' mean?", options: ["sick person", "able to wait calmly", "doctor", "medicine"], correct: 1 }
  ],

  math: [
    { question: "2 + 2 = ?", options: ["3", "4", "5", "6"], correct: 1 },
    { question: "10 × 5 = ?", options: ["45", "50", "55", "60"], correct: 1 },
    { question: "100 ÷ 4 = ?", options: ["20", "25", "30", "35"], correct: 1 },
    { question: "5² = ?", options: ["10", "15", "25", "30"], correct: 2 },
    { question: "√16 = ?", options: ["2", "3", "4", "5"], correct: 2 },
    { question: "20% of 100 = ?", options: ["10", "20", "30", "40"], correct: 1 },
    { question: "3 + 4 × 2 = ?", options: ["11", "14", "10", "12"], correct: 1 },
    { question: "15 - 7 = ?", options: ["7", "8", "9", "10"], correct: 1 },
    { question: "6 × 7 = ?", options: ["40", "42", "44", "46"], correct: 1 },
    { question: "Uchburchak nechta burchakka ega?", options: ["2", "3", "4", "5"], correct: 1 },
    { question: "12 + 8 = ?", options: ["19", "20", "21", "22"], correct: 1 },
    { question: "50 ÷ 2 = ?", options: ["20", "25", "30", "35"], correct: 1 },
    { question: "9 × 9 = ?", options: ["81", "80", "82", "79"], correct: 0 },
    { question: "30% of 50 = ?", options: ["10", "15", "20", "25"], correct: 1 },
    { question: "8² = ?", options: ["64", "63", "65", "62"], correct: 0 },
    { question: "√25 = ?", options: ["4", "5", "6", "7"], correct: 1 },
    { question: "100 - 45 = ?", options: ["55", "54", "56", "57"], correct: 0 },
    { question: "7 × 8 = ?", options: ["54", "55", "56", "57"], correct: 2 },
    { question: "25% of 80 = ?", options: ["15", "20", "25", "30"], correct: 1 },
    { question: "3³ = ?", options: ["9", "27", "81", "243"], correct: 1 },
    { question: "60 ÷ 3 = ?", options: ["15", "20", "25", "30"], correct: 1 },
    { question: "11 + 11 = ?", options: ["21", "22", "23", "24"], correct: 1 },
    { question: "99 - 50 = ?", options: ["48", "49", "50", "51"], correct: 1 },
    { question: "4 × 4 = ?", options: ["16", "15", "14", "13"], correct: 0 },
    { question: "√36 = ?", options: ["5", "6", "7", "8"], correct: 1 },
    { question: "2³ = ?", options: ["6", "8", "10", "12"], correct: 1 },
    { question: "45 + 35 = ?", options: ["80", "81", "82", "79"], correct: 0 },
    { question: "72 ÷ 8 = ?", options: ["8", "9", "10", "11"], correct: 1 },
    { question: "15% of 100 = ?", options: ["10", "15", "20", "25"], correct: 1 },
    { question: "10² = ?", options: ["100", "99", "101", "102"], correct: 0 }
  ],

  uzbek: [
    { question: "O'zbek tili qaysi xalq tili?", options: ["Arab", "Turk", "Hindus", "Qafqaz"], correct: 1 },
    { question: "'Kitob' so'zi nimani anglatadi?", options: ["qalam", "kitob", "daftar", "o'quv vosita"], correct: 1 },
    { question: "O'zbek alifbosida qancha harf bor?", options: ["29", "30", "31", "32"], correct: 1 },
    { question: "Qaysi so'z ko'chma ma'noga ega?", options: ["qalam", "ko'z ochdi", "stol", "daftar"], correct: 1 },
    { question: "'Tug'ilgan kun' qanday turdagi so'z?", options: ["sodda", "murakkab", "qo'shma", "qisqartirilgan"], correct: 2 },
    { question: "O'zbek tilida qancha unli harf?", options: ["4", "5", "6", "7"], correct: 2 },
    { question: "Qaysi so'z sinonim?", options: ["qalam, qalamdan", "kitob, asar", "rang, rangli", "uy, uyning"], correct: 1 },
    { question: "'Shirin' so'zi qaysi so'zning antonimidir?", options: ["sho'r", "pur", "chegara", "biror"], correct: 0 },
    { question: "O'zbek tilida qancha undosh harf?", options: ["20", "21", "22", "23"], correct: 1 },
    { question: "Qaysi so'z oʻz nomdan hosil?", options: ["yashil", "kitob", "qadam", "ot"], correct: 0 },
    { question: "'Oʻquvchi' so'zi qaysi qo'shimchasini oʻz ichiga oladi?", options: ["-chi", "-da", "-ni", "-ning"], correct: 0 },
    { question: "Qaysi so'z sodda?", options: ["o'quvchi", "darslik", "qadam", "ustozi"], correct: 2 },
    { question: "'Shumi' so'zi qaysi fanda qoʻllaniladi?", options: ["musiqa", "sport", "teatr", "kino"], correct: 0 },
    { question: "O'zbek tilida qancha asosiy kesim bor?", options: ["3", "4", "5", "6"], correct: 2 },
    { question: "'Uy' so'zining koʻplik shakli?", options: ["uylar", "uyni", "uyning", "uyda"], correct: 0 },
    { question: "Qaysi so'z xos nom?", options: ["o'quvchi", "Tashkent", "kitob", "qalamdan"], correct: 1 },
    { question: "'Yashil' qaysi so'z turiga mansub?", options: ["ot", "sifat", "ravish", "fe'l"], correct: 1 },
    { question: "O'zbek tilida qancha bog'lovchi bor?", options: ["10", "15", "20", "25"], correct: 2 },
    { question: "'Bari' so'zi qanday ma'nodagi?", options: ["miqdor", "taqqoslash", "vaqt", "joyga oid"], correct: 0 },
    { question: "'Yig'il' so'zining fe'li?", options: ["yig'ilish", "yig'ish", "yig'ilmoq", "yig'ildi"], correct: 2 },
    { question: "Qaysi so'z murakkab?", options: ["daftar", "o'qituvchi", "qalamdan", "uyning"], correct: 1 },
    { question: "'Mustaqil' so'zi qanday mislı?", options: ["ismul-fa'il", "ismul-makan", "ismul-zamon", "ismul-alet"], correct: 0 },
    { question: "'Har' so'zi qanday ma'nodagi?", options: ["taqqoslash", "umumiylik", "nisbat", "joyga oid"], correct: 1 },
    { question: "'Ketdi' so'zi qaysi zamonning?", options: ["hozirgi", "o'tgan", "kelasi", "shartli"], correct: 1 },
    { question: "Qaysi so'z sozi shaxsi bilan oʻzgaradi?", options: ["o'quvchi", "boshlanmoq", "yashil", "tez"], correct: 1 },
    { question: "'Bir' so'zi qanday turda qatnashadi?", options: ["shaxs", "son", "vaqt", "joyga oid"], correct: 1 },
    { question: "'Unga' so'zi qanday bo'lakka mansub?", options: ["ot", "sifat", "ravish", "bog'lovchi"], correct: 2 },
    { question: "O'zbek tilida qancha oraliq zamonmi?", options: ["2", "3", "4", "5"], correct: 1 },
    { question: "'Shu' so'zi qanday ko'rsatma?", options: ["bu", "o'sha", "qaysi", "bunday"], correct: 1 },
    { question: "'Men' qaysi pronoun?", options: ["shaxs", "son", "vaqt", "1-shaxs"], correct: 3 }
  ],

  russian: [
    { question: "Что означает слово 'привет'?", options: ["до свидания", "пока", "привет", "спасибо"], correct: 2 },
    { question: "Какой род у слова 'книга'?", options: ["мужской", "женский", "средний", "общий"], correct: 1 },
    { question: "Сколько падежей в русском языке?", options: ["4", "5", "6", "7"], correct: 2 },
    { question: "Подберите синоним к слову 'большой'?", options: ["маленький", "огромный", "тонкий", "узкий"], correct: 1 },
    { question: "Какой антоним у слова 'холодно'?", options: ["теплый", "горячо", "жарко", "прохладно"], correct: 2 },
    { question: "Что такое глагол?", options: ["часть речи, обозначающая признак", "часть речи, обозначающая действие", "часть речи, обозначающая предмет", "служебная часть речи"], correct: 1 },
    { question: "Сколько букв в русском алфавите?", options: ["31", "32", "33", "34"], correct: 2 },
    { question: "Подберите правильное окончание: 'Я иду в школ...'", options: ["а", "у", "ы", "е"], correct: 1 },
    { question: "Что означает слово 'пустой'?", options: ["полный", "не содержащий ничего", "большой", "маленький"], correct: 1 },
    { question: "Какой род у слова 'письмо'?", options: ["мужской", "женский", "средний", "общий"], correct: 2 },
    { question: "Что такое имя прилагательное?", options: ["часть речи, обозначающая действие", "часть речи, обозначающая признак", "часть речи, обозначающая предмет", "служебная часть речи"], correct: 1 },
    { question: "Выберите правильное множественное число: 'дом'", options: ["домов", "домы", "домо", "домы"], correct: 1 },
    { question: "Какой род у слова 'окно'?", options: ["мужской", "женский", "средний", "общий"], correct: 2 },
    { question: "Подберите нужное слово: 'Я ____ в школу.'", options: ["хожу", "идешь", "идет", "идут"], correct: 0 },
    { question: "Что означает слово 'грустный'?", options: ["веселый", "печальный", "умный", "добрый"], correct: 1 },
    { question: "Какой род у слова 'мать'?", options: ["мужской", "женский", "средний", "общий"], correct: 1 },
    { question: "Выберите правильное окончание: 'Она красив...'", options: ["ый", "ая", "ое", "ые"], correct: 1 },
    { question: "Что означает слово 'светлый'?", options: ["темный", "яркий", "холодный", "теплый"], correct: 1 },
    { question: "Подберите правильное слово: 'Я ____ читаю.'", options: ["медленно", "медленный", "медлить", "медленный"], correct: 0 },
    { question: "Какой род у слова 'стол'?", options: ["мужской", "женский", "средний", "общий"], correct: 0 },
    { question: "Что означает слово 'добрый'?", options: ["злой", "хороший", "плохой", "честный"], correct: 1 },
    { question: "Выберите правильное множественное число: 'кот'", options: ["коты", "кота", "котов", "кот"], correct: 0 },
    { question: "Подберите нужное слово: 'Ты ____ работаешь.'", options: ["хорошо", "хороший", "хорошим", "хорошей"], correct: 0 },
    { question: "Что означает слово 'умный'?", options: ["глупый", "способный", "ленивый", "усталый"], correct: 1 },
    { question: "Какой род у слова 'студент'?", options: ["мужской", "женский", "средний", "общий"], correct: 0 },
    { question: "Выберите правильное окончание: 'Он высок...'", options: ["ый", "ая", "ое", "ие"], correct: 0 },
    { question: "Что означает слово 'быстрый'?", options: ["медленный", "скорый", "ленивый", "интересный"], correct: 1 },
    { question: "Как пишется слово 'встреча'?", options: ["встреча", "встреча", "встреча", "встреча"], correct: 0 },
    { question: "Сколько звуков в слове 'школа'?", options: ["5", "6", "7", "4"], correct: 0 },
    { question: "Что означает слово 'интересный'?", options: ["скучный", "привлекающий внимание", "плохой", "хороший"], correct: 1 }
  ]
};